#Author: Ilia Awudetsey
#Description: For privacy, this template is left in place of the real application.properties. It holds all of the
#database configuration details and credentials.

spring.application.name=APPLICATION_NAME

spring.datasource.url=PROTOCOL://HOST_ADDRESS:PORT/DATABASE_NAME
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=create-drop

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
